server.port: 80
pet-clinic:
  host-name: my-pet.com
  name: Aibolit
  working-hours:
    start: 8AM
    end: 5PM
  doctor-url: "http://localhost:8081"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
logging.level:
    sql: debug
    org.springframework.web.client: debug

---
spring.profiles: europe
pet-clinic:
  working-hours:
    start: 9AM
    end: 6PM

---
spring.profiles: test
pet-clinic:
  doctor-url: "http://localhost:8089"
#...